name: Cache Yarn
description: 'Cache Yarn dependencies'

runs:
  using: 'composite'
  steps:
    - name: Cache path
      id: yarn-cache-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
